// <auto-generated />
namespace SI_Dital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SIDital4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SIDital4));
        
        string IMigrationMetadata.Id
        {
            get { return "202012140300491_SI-Dital-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
